apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "web"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: web
        image: momscritical/ssg-web:v1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  ports:
    - name: web-port
      port: 9001
      targetPort: 80
      # nodePort: 32706
  selector:
    app: web
  type: ClusterIP